# Generated by Django 5.1.7 on 2025-03-20 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(default='app_user/avatars/default.png', upload_to='app_user/avatars/', verbose_name='Ссылка')),
                ('alt', models.CharField(max_length=255, verbose_name='Альтернативный текст')),
            ],
            options={
                'verbose_name': 'Аватар',
                'verbose_name_plural': 'Аватары',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('phone', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Телефон')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс')),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='user.avatarimage', verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
