# Generated by Django 5.1.7 on 2025-03-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryimage',
            options={'verbose_name': 'Изображение категории', 'verbose_name_plural': 'Изображения категорий'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение продукта', 'verbose_name_plural': 'Изображения продуктов'},
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='product.review', verbose_name='Отзывы'),
        ),
    ]
