# Generated by Django 5.1.7 on 2025-03-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentPage', models.PositiveIntegerField(default=1, verbose_name='Текущая страница')),
                ('lastPage', models.PositiveIntegerField(verbose_name='Последняя страница')),
                ('items', models.ManyToManyField(to='product.product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Каталог',
            },
        ),
    ]
