# Generated by Django 5.1.7 on 2025-03-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dateForm',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала скидки'),
        ),
        migrations.AddField(
            model_name='product',
            name='dateTo',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания скидки'),
        ),
        migrations.AddField(
            model_name='product',
            name='salePrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Скидка'),
        ),
    ]
