# Generated by Django 5.1.7 on 2025-03-22 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0008_product_dateform_product_dateto_product_saleprice'),
        ('user', '0002_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namber', models.CharField(max_length=255, verbose_name='Номер карты')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('month', models.CharField(max_length=255, verbose_name='Месяц')),
                ('year', models.CharField(max_length=255, verbose_name='Год')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('fullName', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('deliveryType', models.CharField(max_length=255, verbose_name='Доставка')),
                ('paymentType', models.CharField(max_length=255, verbose_name='Оплата')),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('status', models.CharField(default=False, max_length=100, verbose_name='Статус')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('products', models.ManyToManyField(to='product.product', verbose_name='Товары')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
