# Generated by Django 5.1.7 on 2025-03-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryType',
            field=models.CharField(blank=True, default='ordinary', max_length=255, null=True, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentType',
            field=models.CharField(blank=True, default='online', max_length=255, null=True, verbose_name='Оплата'),
        ),
    ]
